### ISSUE TITLE
建議將本教學中的使用的 'Patch'一詞修改為'Commit'

### ISSUE THREAD

**Issue by w84miracle** [zlargon/git-tutorial#2]
在許多其他教學及文件中皆以 commit 來稱呼，且Git 本身中的 patch 也[另有所指](https://git-scm.com/docs/git-format-patch)
而作者文中提到的patch 應該都是指commit，因此建議將 patch 改以 commit 稱呼避免混淆

**Comment by zlargon** [comment]
@w84miracle

感謝你的提醒
如果造成你的混肴，先跟你說聲抱歉 😉
我之後會在教學裡面附註 commit 跟 patch 的解釋
不過，其實我會選用 "patch" 的名詞來取代 "commit" 是有原因的

首先，commit 在英文裡面是當動詞 "犯罪；託付"，但沒有名詞的字義
雖然 git 的作者 Linus Torvalds 已經把 "commit" 完全名詞化了...
其實說不定這是某種的英式用法.... 🤔

另外，我覺得寫 "commit a commit" 很饒口，所以才擅自改用 patch 來替代 "名詞的 commit"
會選擇用 "patch" 也是因為我知道 git 有 format-patch 的功能，意義上算是滿相近的：
format-patch → 將 patch 格式化，生成實體檔案（patch 可以包含一個或多個 commit）

最後，format-patch 功能算是滿少見的
我目前只有看過開源專案 FFmpeg 要求貢獻者使用 format-patch, send-mail 來提交原始碼
所以我想對於 git 的 _初學者_ 來說，應該是不至於造成混淆
你會知道到 format-patch 的指令，表示你對 git 已經相當熟悉囉！

因此，這個教學我還是會維持使用 patch 這個用詞
但我會另外附註 commit 跟 patch 的解釋
再次感謝 😀

**Comment by w84miracle** [comment]
在 IT 界有很多詞彙都是額外衍生的新義，可以不用拘泥於是否符合舊有的字義
一個有趣的例子是以 [Git](https://en.oxforddictionaries.com/definition/git) 來說，在英文裡其實原本是貶義的詞彙

"commit a commit"的確饒口，所以老外為了避免此用法通常會使用 "create/make a commit"
且commit 同時當動詞及名詞使用應該算一個共識了，各Git相關的服務或是軟體也以 commit 稱之
如下圖應該大家都不陌生:
![image](https://cloud.githubusercontent.com/assets/1922754/21254723/2a684a7a-c3a2-11e6-9d65-6f14faf0b32c.png)

因此，如果要使用英文的話還是建議使用原文的commit，或是可以考慮使用"提交"一詞也是常見的中譯
不過如果有另外附註確實也能降低初學者混淆的機率
如果作者打算繼續使用 "patch" 的話就可以關閉這個 issue 了

**Comment by zlargon** [comment]
我想我表達得很清楚囉~
我的目的就是為了避免初學者對 commit (v.) 跟 commit (n.) 造成混淆
所以才刻意用 patch 來代替稱呼 commit (n.)

我相信這個教學裡面所有的觀念都是非常清楚正確的
使用 "patch" 一詞並沒有造成學習觀念上的混淆
至於能不能接受，就是你的個人自由囉~

By the way, "Git" 一詞是 Linus Torvalds 故意自嘲是 "混蛋"，並出自於這句話：

___I'm an egotistical bastard, and I name all my projects after myself. First Linux, now git.___
